# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
    tags: "v*"
  pull_request:
    branches: ["main"]

env:
  GoVersion: 1.21

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GoVersion }}

      - name: Build
        run: go build -v ./...

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GoVersion }}

      - name: Genetate Data For Test
        run: sh ./scripts/create_test_data.sh

      - name: Test
        run: go test -timeout 3h -v ./...

  release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GoVersion }}

      - name: Install zip
        run: sudo apt install zip

      - name: "Build"
        env:
          tag: ${{ github.ref_name }}
        run: |
          # Linux AMD64
          env GOOS=linux GOARCH=amd64 go build -ldflags="-X 'vineelsai.com/checkout/src.Version=$tag'"
          tar -czvf checkout-linux-amd64.tar.gz checkout

          # Linux ARM64
          env GOOS=linux GOARCH=arm64 go build -ldflags="-X 'vineelsai.com/checkout/src.Version=$tag'"
          tar -czvf checkout-linux-arm64.tar.gz checkout

          # MacOS AMD64
          env GOOS=darwin GOARCH=amd64 go build -ldflags="-X 'vineelsai.com/checkout/src.Version=$tag'"
          tar -czvf checkout-macos-amd64.tar.gz checkout
          go clean

          # MacOS ARM64
          env GOOS=darwin GOARCH=arm64 go build -ldflags="-X 'vineelsai.com/checkout/src.Version=$tag'"
          tar -czvf checkout-macos-arm64.tar.gz checkout
          go clean

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.RELEASE_TOKEN }}"
          prerelease: false
          files: |
            *.tar.gz
